{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6c975fad",
   "metadata": {},
   "outputs": [],
   "source": [
    "#pip install dask[complete] dask-ml pandas scikit-learn\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "0ad7e679",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import dask.dataframe as dd\n",
    "import dask_ml.model_selection as dml\n",
    "from dask_ml.model_selection import train_test_split\n",
    "\n",
    "import dask_ml.metrics as dmm\n",
    "from dask_ml.linear_model import LogisticRegression\n",
    "from dask.distributed import Client\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "232ba9a9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cargar los datos con Dask\n",
    "df = pd.read_csv('..\\data\\ENPOVE2022_V_200-300-400-500-600-700-800.csv')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "d4128936",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Definir las variables\n",
    "variables_a_excluir = [\n",
    "    'CCDD', 'DEPARTAMENTO', 'CCPP', 'PROVINCIA', 'CCDI', 'DISTRITO',\n",
    "    'CIUDAD', 'CONGLOMERADO', 'NSELV', 'VIVIENDA', 'THOGAR', 'NHOGAR',\n",
    "    'ESTRATO', 'VRESFIN', 'RESFIN', 'P15', 'P15_N', 'INF_200', 'P200_N',\n",
    "    'P609_COD', 'P611_COD', 'P625A_COD_DEPA', 'P625_COD_PROV', 'P625_COD_DIST',\n",
    "    'factorfinal', 'P602'\n",
    "]\n",
    "\n",
    "# Obtener la lista de todas las columnas\n",
    "todas_las_columnas = df.columns.tolist()\n",
    "\n",
    "# Determinar las covariables (X) excluyendo las especificadas\n",
    "columnas_covariables = [col for col in todas_las_columnas if col not in variables_a_excluir]\n",
    "\n",
    "# Definir predictores (X) y target (y)\n",
    "X = df[columnas_covariables]\n",
    "y = df['P602']  # Empleo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "932b3901",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\deploy\\spec.py:285: UserWarning: \n",
      "Could not launch service 'dashboard' on port 8787. Got the following message:\n",
      "\n",
      "failed to validate _ServerOpts(...).prefix: expected a value of type str, got None of type NoneType\n",
      "  self.scheduler = await self.scheduler\n",
      "distributed.utils - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\utils.py\", line 662, in log_errors\n",
      "    yield\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.core - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 408, in handle_comm\n",
      "    result = handler(comm, **msg)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.utils - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\utils.py\", line 662, in log_errors\n",
      "    yield\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.core - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 408, in handle_comm\n",
      "    result = handler(comm, **msg)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.protocol.core - CRITICAL - Failed to deserialize\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n",
      "distributed.utils - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\utils.py\", line 662, in log_errors\n",
      "    yield\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.core - ERROR - addresses should be strings or tuples, got None\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 408, in handle_comm\n",
      "    result = handler(comm, **msg)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 2126, in remove_worker\n",
      "    address = self.coerce_address(address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\scheduler.py\", line 4836, in coerce_address\n",
      "    raise TypeError(\"addresses should be strings or tuples, got %r\" % (addr,))\n",
      "TypeError: addresses should be strings or tuples, got None\n",
      "distributed.protocol.core - CRITICAL - Failed to deserialize\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n",
      "tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x0000020C4DD51FA0>>, <Task finished name='Task-3346' coro=<Nanny._on_exit() done, defined at C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py:388> exception=ValueError('tuple is not allowed for map key when strict_map_key=True')>)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 765, in _discard_future_result\n",
      "    future.result()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py\", line 391, in _on_exit\n",
      "    await self.scheduler.unregister(address=self.worker_address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 757, in send_recv_from_rpc\n",
      "    result = await send_recv(comm=comm, op=key, **kwargs)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 540, in send_recv\n",
      "    response = await comm.read(deserializers=deserializers)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\tcp.py\", line 211, in read\n",
      "    msg = await from_frames(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 69, in from_frames\n",
      "    res = _from_frames()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 54, in _from_frames\n",
      "    return protocol.loads(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n",
      "tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x0000020C4DD51FA0>>, <Task finished name='Task-3344' coro=<Nanny._on_exit() done, defined at C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py:388> exception=ValueError('tuple is not allowed for map key when strict_map_key=True')>)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 765, in _discard_future_result\n",
      "    future.result()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py\", line 391, in _on_exit\n",
      "    await self.scheduler.unregister(address=self.worker_address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 757, in send_recv_from_rpc\n",
      "    result = await send_recv(comm=comm, op=key, **kwargs)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 540, in send_recv\n",
      "    response = await comm.read(deserializers=deserializers)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\tcp.py\", line 211, in read\n",
      "    msg = await from_frames(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 69, in from_frames\n",
      "    res = _from_frames()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 54, in _from_frames\n",
      "    return protocol.loads(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "distributed.protocol.core - CRITICAL - Failed to deserialize\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n",
      "tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x0000020C4DD51FA0>>, <Task finished name='Task-3347' coro=<Nanny._on_exit() done, defined at C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py:388> exception=ValueError('tuple is not allowed for map key when strict_map_key=True')>)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\tornado\\ioloop.py\", line 765, in _discard_future_result\n",
      "    future.result()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\nanny.py\", line 391, in _on_exit\n",
      "    await self.scheduler.unregister(address=self.worker_address)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 757, in send_recv_from_rpc\n",
      "    result = await send_recv(comm=comm, op=key, **kwargs)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\core.py\", line 540, in send_recv\n",
      "    response = await comm.read(deserializers=deserializers)\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\tcp.py\", line 211, in read\n",
      "    msg = await from_frames(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 69, in from_frames\n",
      "    res = _from_frames()\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\comm\\utils.py\", line 54, in _from_frames\n",
      "    return protocol.loads(\n",
      "  File \"C:\\Users\\Alvaro\\anaconda3\\lib\\site-packages\\distributed\\protocol\\core.py\", line 106, in loads\n",
      "    header = msgpack.loads(header, use_list=False, **msgpack_opts)\n",
      "  File \"msgpack/_unpacker.pyx\", line 194, in msgpack._cmsgpack.unpackb\n",
      "ValueError: tuple is not allowed for map key when strict_map_key=True\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Configuración del cliente Dask\n",
    "client = Client()\n",
    "\n",
    "# División de datos en entrenamiento y prueba\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, \n",
    "    test_size=0.2, \n",
    "    random_state=4200, \n",
    "    shuffle=True  # Explicitly set shuffle\n",
    ")\n",
    "# Definir el modelo\n",
    "model = LogisticRegression()\n",
    "\n",
    "# Definir el grid para GridSearch\n",
    "param_grid = {\n",
    "    'penalty': ['l1', 'l2'],\n",
    "    'C': [0.1, 1, 10]\n",
    "}\n",
    "\n",
    "# Configurar GridSearchCV\n",
    "grid_search = dml.GridSearchCV(model, param_grid, cv=5, scoring='accuracy')\n",
    "\n",
    "# Ajustar el modelo usando GridSearchCV\n",
    "grid_search.fit(X_train, y_train)\n",
    "\n",
    "# Selección del modelo óptimo\n",
    "best_model = grid_search.best_estimator_\n",
    "\n",
    "# Evaluación en el conjunto de entrenamiento\n",
    "y_train_pred = best_model.predict(X_train)\n",
    "train_accuracy = dmm.accuracy_score(y_train, y_train_pred)\n",
    "train_roc_auc = dmm.roc_auc_score(y_train, best_model.predict_proba(X_train)[:, 1])\n",
    "\n",
    "# Evaluación en el conjunto de prueba\n",
    "y_test_pred = best_model.predict(X_test)\n",
    "test_accuracy = dmm.accuracy_score(y_test, y_test_pred)\n",
    "test_roc_auc = dmm.roc_auc_score(y_test, best_model.predict_proba(X_test)[:, 1])\n",
    "\n",
    "# Imprimir resultados\n",
    "print(\"Mejores parámetros encontrados:\")\n",
    "print(grid_search.best_params_)\n",
    "\n",
    "print(\"\\nIndicadores de calidad de ajuste en entrenamiento:\")\n",
    "print(f\"Accuracy: {train_accuracy}\")\n",
    "print(f\"ROC AUC: {train_roc_auc}\")\n",
    "\n",
    "print(\"\\nIndicadores de calidad de ajuste en prueba:\")\n",
    "print(f\"Accuracy: {test_accuracy}\")\n",
    "print(f\"ROC AUC: {test_roc_auc}\")\n",
    "\n",
    "# Reporte de clasificación para la muestra de prueba\n",
    "from dask_ml.metrics import classification_report\n",
    "print(\"\\nReporte de clasificación en prueba:\")\n",
    "print(classification_report(y_test, y_test_pred))\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12f9816d",
   "metadata": {},
   "source": [
    "## Limitaciones y posibles extensiones\n",
    "1. El ajuste del modelo puede no ser óptimo si el grid de búsqueda es pequeño\n",
    "2. Los indicadores de calidad de ajuste dependen de la calidad de los datos.\n",
    "3. Se podría usar una mayor variedad de modelos y técnicas para comparación.\n",
    "4. La escalabilidad puede ser un problema con datasets extremadamente grandes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc85bbab",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "23559536",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bf0716f3",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fffc303d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
